name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See https://github.com/lowlighter/metrics/blob/master/action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: jopemachine
          template: classic
          base: activity, community, repositories
          config_timezone: Asia/Seoul
          plugin_followup: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_ignored: "html, css" # List of comma separated languages to ignore
          plugin_languages_skipped: "" # List of comma separated repositories to skip
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_stargazers: yes
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_limit: 15
          plugin_traffic: yes
          config_output: svg
          config_padding: 12%          
          config_order: base.header, base.repositories, base.activity+community, languages, followup, isocalendar, stargazers, habits
