name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See https://github.com/lowlighter/metrics/blob/master/action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: jopemachine
          template: classic
          base: activity, community, repositories
          config_timezone: Asia/Seoul
          
          plugin_lines: yes
          
          plugin_followup: yes
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage             # Additionally display total bytes size and percentage
          plugin_languages_threshold: 2%                               # Hides all languages less than 2% (🚧 @master feature)
          
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_stargazers: yes
          
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_limit: 15
          plugin_topics_visibility: all
          
          plugin_traffic: yes
          
          plugin_activity: yes
          plugin_activity_limit: 5    # Limit to 5 events
          plugin_activity_days: 14    # Keep only events from last 14 days (can be set to 0 to disable limitations)
          plugin_activity_filter: push, pr, issue, comment, review, fork # Show all events (use table above to filter events types):  
          plugin_activity_visibility: public
          plugin_activity_timestamps: yes

          config_output: svg
          config_padding: 5%          
          config_order: base.header, base.repositories, base.activity+community, languages, followup, license, isocalendar, stargazers, habits, activity

